export default [
  {
    name: 'Mango',
    color: 'Yellow',
    quantity: 12,
    country_of_origin: 'India',
    price: 1.5,
  },
  {
    name: 'Strawberry',
    color: 'Red',
    quantity: 25,
    country_of_origin: 'Spain',
    price: 3.0,
  },
  {
    name: 'Pineapple',
    color: 'Yellow-Green',
    quantity: 8,
    country_of_origin: 'Costa Rica',
    price: 4.0,
  },
  {
    name: 'Banana',
    color: 'Yellow',
    quantity: 30,
    country_of_origin: 'Ecuador',
    price: 0.75,
  },
  {
    name: 'Watermelon',
    color: 'Green-Red',
    quantity: 6,
    country_of_origin: 'Brazil',
    price: 7.5,
  },
  {
    name: 'Orange',
    color: 'Orange',
    quantity: 20,
    country_of_origin: 'Florida',
    price: 1.25,
  },
  {
    name: 'Apple',
    color: 'Red-Green',
    quantity: 40,
    country_of_origin: 'Washington',
    price: 1.0,
  },
  {
    name: 'Grapefruit',
    color: 'Pink-Yellow',
    quantity: 15,
    country_of_origin: 'Texas',
    price: 2.0,
  },
  {
    name: 'Pear',
    color: 'Green-Yellow',
    quantity: 18,
    country_of_origin: 'Italy',
    price: 1.75,
  },
  {
    name: 'Lemon',
    color: 'Yellow',
    quantity: 28,
    country_of_origin: 'California',
    price: 0.8,
  },
];
